### ISSUE TITLE
请教：qca-ssdk和kmod-shortcut-fe-drv在这个源码下能正常编译吗？

### ISSUE THREAD

**Issue by hzjnet** [jollaman999/openwrt#1]
如题，谢谢
尝试过多个版本，不能正常编译，但是shortcut-fe和fast-classifier能正常编译和使用

**Comment by jollaman999** [comment]
Thank you for using my source!

**Comment by hzjnet** [comment]
how can I build qca-nss  for this source?

**Comment by jollaman999** [comment]
@hzjnet In my memories, I think Qualcomm's qca-nss source is based on 3.18 kernel.
It is hard to porting this to our new kernel. So I just removed it from my source.
