### ISSUE TITLE
For example, can ipq4019 be used?

### ISSUE THREAD

**Issue by suyuan168** [jollaman999/openwrt#4]
Excuse me

update_qca-shortcut-fe.sh
update_qca-ssdk.sh
Can it still be used? For example, can ipq4019 be used?

**Comment by jollaman999** [comment]
First, sorry for late reply.

I have left for reference URLs for qca git repositories.
I am constantly applying latest qca patches to my source.
So, you do not need update qca sources.

I'm using ipq806x based machine.
I'm not sure, but ipq40xx will similar with ipq806x.
So, I think you can build your own firmware with some modifies.

**Comment by suyuan168** [comment]
Sorry, I only apply. Can you modify it to an application compatible with ipq40xx? thank you very much

**Comment by jollaman999** [comment]
I don't have ipq40xx device. It is hard to test. Sorry.
