### ISSUE TITLE
ath10k-firmware-qca988x and ath10k-firmware-qca99x0 issue

### ISSUE THREAD

**Issue by jack338c** [jollaman999/openwrt#5]
Hello
I try to build my netgear r7500 v2 with your repo (ath10k-firmware-qca988x and ath10k-firmware-qca99x0)
but got following errors

Would you please hlep me to solve this issue
thank you 

`Receiving objects: 100% (2145/2145), 67.01 MiB | 1.41 MiB/s, done.
Resolving deltas: 100% (1073/1073), done.
Note: switching to '076160b4357ff39db59bac13993011caee820934'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 076160b QCA9984 hw1.0: 3.9.0.2: add firmware-5.bin_10.4-3.9.0.2-00148
Packing checkout...
touch /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.prepared_7cb233038f973c8c7860fa3e7bf76e1e_6664517399ebbbc92a37c5bb081b5c53_check
. /home/x250/jolla999/include/shell.sh; xzcat /home/x250/jolla999/dl/ath10k-firmware-2021-05-21-076160b4.tar.xz | tar -C /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4
touch /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.prepared_7cb233038f973c8c7860fa3e7bf76e1e_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.configured_*
rm -f /home/x250/jolla999/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.ath10k-firmware_installed
(cd /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/./; if [ -x ./configure ]; then find /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ -name config.guess | xargs -r chmod u+w; find /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ -name config.guess | xargs -r -n1 cp --remove-destination /home/x250/jolla999/scripts/config.guess; find /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ -name config.sub | xargs -r chmod u+w; find /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ -name config.sub | xargs -r -n1 cp --remove-destination /home/x250/jolla999/scripts/config.sub; AR="arm-openwrt-linux-muslgnueabi-gcc-ar" AS="ccache_cc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4=ath10k-firmware-2021-05-21-076160b4 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=arm-openwrt-linux-muslgnueabi-ld NM="arm-openwrt-linux-muslgnueabi-gcc-nm" CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB="arm-openwrt-linux-muslgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-muslgnueabi-strip OBJCOPY=arm-openwrt-linux-muslgnueabi-objcopy OBJDUMP=arm-openwrt-linux-muslgnueabi-objdump SIZE=arm-openwrt-linux-muslgnueabi-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4=ath10k-firmware-2021-05-21-076160b4 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4=ath10k-firmware-2021-05-21-076160b4 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/x250/jolla999/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/usr/include -I/home/x250/jolla999/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify -I/home/x250/jolla999/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/include " LDFLAGS="-L/home/x250/jolla999/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/usr/lib -L/home/x250/jolla999/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/lib -znow -zrelro "   ./configure --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.built
touch /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.built_check
touch /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.built
mkdir -p /home/x250/jolla999/bin/targets/ipq806x/generic/packages /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x/CONTROL /home/x250/jolla999/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/pkginfo
install -d -m0755 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x/lib/firmware/ath10k/QCA988X/hw2.0
install -m0644 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/QCA988X/hw2.0/board.bin /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x/lib/firmware/ath10k/QCA988X/hw2.0/
install -m0644 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/QCA988X/hw2.0/10.2.4-1.0/firmware-5.bin_10.2.4-1.0-00047 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x/lib/firmware/ath10k/QCA988X/hw2.0/firmware-5.bin
find /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="arm-openwrt-linux-muslgnueabi-"  NO_RENAME=1 ; NM="arm-openwrt-linux-muslgnueabi-nm" STRIP="/home/x250/jolla999/staging_dir/host/bin/sstrip -z" STRIP_KMOD="/home/x250/jolla999/scripts/strip-kmod.sh" PATCHELF="/home/x250/jolla999/staging_dir/host/bin/patchelf" /home/x250/jolla999/scripts/rstrip.sh /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x
(cd /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /home/x250/jolla999/bin/packages/arm_cortex-a15_neon-vfpv4/base
/home/x250/jolla999/staging_dir/host/bin/fakeroot /home/x250/jolla999/scripts/ipkg-build -m "" /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x /home/x250/jolla999/bin/packages/arm_cortex-a15_neon-vfpv4/base
Packaged contents of /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca988x into /home/x250/jolla999/bin/packages/arm_cortex-a15_neon-vfpv4/base/ath10k-firmware-qca988x_2021-05-21-076160b4-1_arm_cortex-a15_neon-vfpv4.ipk
rm -rf /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.pkgdir/ath10k-firmware-qca988x.installed /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.pkgdir/ath10k-firmware-qca988x
mkdir -p /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.pkgdir/ath10k-firmware-qca988x
install -d -m0755 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.pkgdir/ath10k-firmware-qca988x/lib/firmware/ath10k/QCA988X/hw2.0
install -m0644 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/QCA988X/hw2.0/board.bin /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.pkgdir/ath10k-firmware-qca988x/lib/firmware/ath10k/QCA988X/hw2.0/
install -m0644 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/QCA988X/hw2.0/10.2.4-1.0/firmware-5.bin_10.2.4-1.0-00047 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.pkgdir/ath10k-firmware-qca988x/lib/firmware/ath10k/QCA988X/hw2.0/firmware-5.bin
touch /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/.pkgdir/ath10k-firmware-qca988x.installed
mkdir -p /home/x250/jolla999/bin/targets/ipq806x/generic/packages /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca99x0/CONTROL /home/x250/jolla999/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/pkginfo
install -d -m0755 /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca99x0/lib/firmware/ath10k/QCA99X0/hw2.0
install -m0644 /home/x250/jolla999/dl/ /home/x250/jolla999/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-21-076160b4/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca99x0/lib/firmware/ath10k/QCA99X0/hw2.0/board-2.bin
install: omitting directory '/home/x250/jolla999/dl/'
make[2]: *** [Makefile:186: /home/x250/jolla999/bin/packages/arm_cortex-a15_neon-vfpv4/base/ath10k-firmware-qca99x0_2021-05-21-076160b4-1_arm_cortex-a15_neon-vfpv4.ipk] Error 1
make[2]: Leaving directory '/home/x250/jolla999/package/firmware/ath10k-firmware'
time: package/firmware/ath10k-firmware/compile#66.91#5.06#111.78
    ERROR: package/firmware/ath10k-firmware failed to build.
make[1]: *** [package/Makefile:116: package/firmware/ath10k-firmware/compile] Error 1
make[1]: Leaving directory '/home/x250/jolla999'
make: *** [/home/x250/jolla999/include/toplevel.mk:230: package/firmware/ath10k-firmware/compile] Error 2
`

**Comment by jollaman999** [comment]
@jack338c Need to show full log.
But in my case, you should turn off all of `CONFIG_PACKAGE_ath10k-board-XXXXXX` in your `.config` file.
Try to build with turn off these options and please give me feedback again. Thanks.

**Comment by jack338c** [comment]
@jollaman999 
Ok,I will try 
many thanks !

**Comment by jack338c** [comment]
@jollaman999 

I just use your newest fresh openwrt to build my ea7500 v1 ,but still got issues on ath10k (turn off all of CONFIG_PACKAGE_ath10k-board-XXXXXX or turn on ,no works)
Could you tell me any idea?
thank you
`ath10k-firmware-2021-05-28-718044dd.tar.xz: Download from https://github.com/kvalo/ath10k-firmware.git failed
ath10k-firmware-2021-05-28-718044dd.tar.xz: Requires sha256sum for verification
Checking out files from the git repository...
Cloning into 'ath10k-firmware-2021-05-28-718044dd'...
remote: Enumerating objects: 2187, done.
remote: Counting objects: 100% (358/358), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 2187 (delta 211), reused 272 (delta 131), pack-reused 1829
Receiving objects: 100% (2187/2187), 68.53 MiB | 6.96 MiB/s, done.
Resolving deltas: 100% (1100/1100), done.
Note: switching to '718044ddcc1ad84466b69cebe144023e2dd342a0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 718044d QCA9984 hw1.0: 3.9.0.2: add firmware-5.bin_10.4-3.9.0.2-00149
Packing checkout...
touch /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/.prepared_d058602186a4c7c1b4dc0c76363370d9_6664517399ebbbc92a37c5bb081b5c53_check
. /home/x250/jollaman3/include/shell.sh; xzcat /home/x250/jollaman3/dl/ath10k-firmware-2021-05-28-718044dd.tar.xz | tar -C /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd
touch /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/.prepared_d058602186a4c7c1b4dc0c76363370d9_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/.configured_*
rm -f /home/x250/jollaman3/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.ath10k-firmware_installed
(cd /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/./; if [ -x ./configure ]; then find /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/ -name config.guess | xargs -r chmod u+w; find /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/ -name config.guess | xargs -r -n1 cp --remove-destination /home/x250/jollaman3/scripts/config.guess; find /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/ -name config.sub | xargs -r chmod u+w; find /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/ -name config.sub | xargs -r -n1 cp --remove-destination /home/x250/jollaman3/scripts/config.sub; AR="arm-openwrt-linux-muslgnueabi-gcc-ar" AS="ccache_cc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd=ath10k-firmware-2021-05-28-718044dd -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=arm-openwrt-linux-muslgnueabi-ld NM="arm-openwrt-linux-muslgnueabi-gcc-nm" CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB="arm-openwrt-linux-muslgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-muslgnueabi-strip OBJCOPY=arm-openwrt-linux-muslgnueabi-objcopy OBJDUMP=arm-openwrt-linux-muslgnueabi-objdump SIZE=arm-openwrt-linux-muslgnueabi-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd=ath10k-firmware-2021-05-28-718044dd -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd=ath10k-firmware-2021-05-28-718044dd -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/x250/jollaman3/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/usr/include -I/home/x250/jollaman3/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify -I/home/x250/jollaman3/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/include " LDFLAGS="-L/home/x250/jollaman3/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/usr/lib -L/home/x250/jollaman3/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.4.0_musl_eabi/lib -znow -zrelro "   ./configure --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/.built
touch /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/.built_check
touch /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/.built
mkdir -p /home/x250/jollaman3/bin/targets/ipq806x/generic/packages /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca99x0/CONTROL /home/x250/jollaman3/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/pkginfo
install -d -m0755 /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca99x0/lib/firmware/ath10k/QCA99X0/hw2.0
install -m0644 /home/x250/jollaman3/dl/ /home/x250/jollaman3/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/ath10k-firmware-2021-05-28-718044dd/ipkg-arm_cortex-a15_neon-vfpv4/ath10k-firmware-qca99x0/lib/firmware/ath10k/QCA99X0/hw2.0/board-2.bin
install: omitting directory '/home/x250/jollaman3/dl/'
make[2]: *** [Makefile:186: /home/x250/jollaman3/bin/packages/arm_cortex-a15_neon-vfpv4/base/ath10k-firmware-qca99x0_2021-05-28-718044dd-1_arm_cortex-a15_neon-vfpv4.ipk] Error 1
make[2]: Leaving directory '/home/x250/jollaman3/package/firmware/ath10k-firmware'
time: package/firmware/ath10k-firmware/compile#65.15#3.13#75.01
    ERROR: package/firmware/ath10k-firmware failed to build.
make[1]: *** [package/Makefile:116: package/firmware/ath10k-firmware/compile] Error 1
make[1]: Leaving directory '/home/x250/jollaman3'
make: *** [/home/x250/jollaman3/include/toplevel.mk:230: package/firmware/ath10k-firmware/compile] Error 2
`
![Screenshot from 2021-06-10 12-00-33](https://user-images.githubusercontent.com/10782586/121462896-e0ba5880-c9e3-11eb-8b57-5f9466385274.png)
![Screenshot from 2021-06-10 12-00-12](https://user-images.githubusercontent.com/10782586/121462901-e2841c00-c9e3-11eb-867b-c7b1b8048d4b.png)

**Comment by jollaman999** [comment]
@jack338c Sorry for my mistake and late reply. I missed board file for 99x0. Could you try it again?

**Comment by jack338c** [comment]
@jollaman999 
I will 
many thanks !

**Comment by jack338c** [comment]
It works !
Thanks again

**Comment by jollaman999** [comment]
@jack338c Perfect! Thanks for using my source. :)

**Comment by jack338c** [comment]
@jollaman999 
the Hardware NAT (qca-ssdk)  is really good !

Today I found the  ath10k-firmware-qca99x0 may have issue on setting up 802.11s (mesh),it's always show "wireless is not associated" after added mesh ap,neither on 2.4g or 5G (but offical openwrt firmware is ok)

and my ex6150 v2 (ath10k-firmware-qca99x0 ) works on setting up 802.11s with your repo

Dose your ZyXEL_NBG6817 have this issue too?

thanks

**Comment by David3434** [comment]
by the way
I just found Kernel Log in my ea7500 v1 like this:

![Screen Shot 2021-06-24 at 6 30 32 AM](https://user-images.githubusercontent.com/55067456/123176308-c7221200-d4b5-11eb-879a-461360c2fa24.png)

**Comment by jollaman999** [comment]
@jack338c I didn't tested 802.11s feature. I will check if there are some issue with my router.

**Comment by jollaman999** [comment]
@David3434 Hi, thank you for using my source.
I will check if there are any differences in target sources with openwrt.
Also, could you provide your `.config` file in your source's root folder?

**Comment by David3434** [comment]
Here is the .config.thanks

[Uploading Untitled Document 1.zip…]()

**Comment by David3434** [comment]
@jollaman999 
I just build a new fresh from openwrt official ,it's same issue
jack338c are my another account
I'm sorry for troubles

**Comment by jack338c** [comment]
I tested it ,change to ath10k-firmware-qca99x0-ct,mesh will work

**Comment by jollaman999** [comment]
@jack338c Hmmm.. So, maybe only ct firmware can handle 802.11s?
It should be have diffrent features but there are no detail informations about stock firmware.

**Comment by jollaman999** [comment]
@jack338c I didn't check cpu clock issue yet. Sorry.
I'm interesting with wireguard new VPN protocol now. And it shows amazing speed.

**Comment by jack338c** [comment]
@jollaman999 
sounds good,I have interest to test it later
I found this https://github.com/ACwifidude/openwrt/commit/4fc9ca2bd87c5ec5520310973ed41d3416887a5b did you test this before?

**Comment by jollaman999** [comment]
@jack338c It looks good. I will cherry-pick and test it.

**Comment by jack338c** [comment]
> @jack338c I didn't check cpu clock issue yet. Sorry.
> I'm interesting with wireguard new VPN protocol now. And it shows amazing speed.

I find the reason for the cpu  issue,it was locked,because too hot

**Comment by jollaman999** [comment]
@jack338c I see. It looks like simillar with thermal throttlig in smart phones.
